### ISSUE TITLE
大佬，求这个cim项目的启动教程和数据库脚本教程.谢谢啦

### ISSUE THREAD

**Issue by doc-laowu** [hexiaoyun128/cim#1]

**Comment by itcloudy** [comment]
django命令就可以启动的，数据库也是一样

**Comment by shin-zou** [comment]
给新手写点教程，下载这个项目后，直接懵逼了。环境一系列下，没有问题，但是要启动这个项目改了好些内容，依然启动不了。

求这个cim项目的启动教程和数据库脚本教程

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 589, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 123, in inner_run
    self.check_migrations()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\core\management\base.py", line 427, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\migrations\loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\migrations\recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\migrations\recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\django\db\backends\postgresql\base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
